### ISSUE TITLE
Add JupyterLite Demo

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab-contrib/jupyter-videochat#40]
## References

- blocked by #39
- blocked by #25
  - some work in progress here #38

## Elevator Pitch

Demonstrate using the JupyterLab extension at a stable, predictable URL that loads faster than a binder, but is more ephemeral in its content, and demonstrates round-about "integration" without fully implementing #28 (still desirable for self-hosting).

## Tasks
- [ ] add `jupyterlite` to docs environment, build
- [ ] add a tour
- [ ] add a widget-based link builder notebook
  - [ ] `JVC-PUBLIC`
  - [ ] `room` that uses the public WebRTC signaling server provided by `yjs`
  - [ ] `workspace`, once supported
  - [ ] ???

**Comment by bollwyvl** [comment]
fixed by #41
